### ISSUE TITLE
Setup CI to run Jasmine tests

### ISSUE THREAD

**Issue by vovka** [superNazo/video_quiz#13]

**Comment by mrJmek** [comment]
**???IMPOSSIBRU???**
https://blog.codeship.com/jasmine-testing-javascript/

https://www.google.com.ua/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=testing+jasmine+at+codeship

**Comment by mrJmek** [comment]
Possibru even with official gem:
https://github.com/jasmine/jasmine-gem

`bundle exec rake jasmine:ci`
